"""Adicionar coluna nome_mae

Revision ID: 0015286984f8
Revises: 
Create Date: 2025-04-05 18:05:10.277737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '0015286984f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Adiciona a coluna como nullable
    op.add_column('abordagem', sa.Column('nome_mae', sa.String(length=100), nullable=True))
    
    # Atualiza os registros existentes
    conn.execute(text("UPDATE abordagem SET nome_mae = 'Não informado'"))
    
    # Torna a coluna NOT NULL
    with op.batch_alter_table('abordagem', schema=None) as batch_op:
        batch_op.alter_column('nome_mae',
               existing_type=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abordagem', schema=None) as batch_op:
        batch_op.drop_column('nome_mae')
    # ### end Alembic commands ###
