"""adicionar_coluna_historico_pca

Revision ID: 76535a76eba8
Revises: 0015286984f8
Create Date: 2025-04-05 18:19:10.122657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76535a76eba8'
down_revision = '0015286984f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abordagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historico_pca', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abordagem', schema=None) as batch_op:
        batch_op.drop_column('historico_pca')

    # ### end Alembic commands ###
