"""adicionar_campos_usuario

Revision ID: f54fde9d0ef6
Revises: 0dfbff9f9ce1
Create Date: 2025-04-05 21:49:11.050513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54fde9d0ef6'
down_revision = '0dfbff9f9ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('ultimo_acesso', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('nivel_acesso', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nivel_acesso')
    op.drop_column('user', 'ultimo_acesso')
    op.drop_column('user', 'data_criacao')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
