"""Initial migration

Revision ID: initial_migration
Revises: 
Create Date: 2025-04-07 18:20:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'initial_migration'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('cargo', sa.String(length=100), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
        sa.Column('nivel_acesso', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )

    op.create_table('abordagem',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome_completo', sa.String(length=100), nullable=False),
        sa.Column('nome_mae', sa.String(length=100), nullable=False),
        sa.Column('vulgo', sa.String(length=50), nullable=True),
        sa.Column('cpf', sa.String(length=14), nullable=True),
        sa.Column('data_nascimento', sa.Date(), nullable=True),
        sa.Column('endereco_abordagem', sa.String(length=200), nullable=False),
        sa.Column('endereco_residencia', sa.String(length=200), nullable=True),
        sa.Column('data_hora', sa.DateTime(), nullable=False),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.Column('imagem', sa.String(length=255), nullable=True),
        sa.Column('historico_pca', sa.String(length=255), nullable=True),
        sa.Column('alerta', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abordagem')
    op.drop_table('user')
    # ### end Alembic commands ### 